// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDArexA7ByC-IfILpMjoq23e67G6hq0c2A',
    appId: '1:668353511665:web:74fc459197c6aace666950',
    messagingSenderId: '668353511665',
    projectId: 'barkgenius-finalproject',
    authDomain: 'barkgenius-finalproject.firebaseapp.com',
    storageBucket: 'barkgenius-finalproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtJmKAOjG4rXmhb7LBF8jlnyD_WygXqsk',
    appId: '1:668353511665:android:4bdf51d0a8626d6f666950',
    messagingSenderId: '668353511665',
    projectId: 'barkgenius-finalproject',
    storageBucket: 'barkgenius-finalproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGau1-IZSqreso8GWn29XvYljZ1LNYhEg',
    appId: '1:668353511665:ios:c97f4a09e99c034d666950',
    messagingSenderId: '668353511665',
    projectId: 'barkgenius-finalproject',
    storageBucket: 'barkgenius-finalproject.appspot.com',
    iosBundleId: 'com.example.barkGeniusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGau1-IZSqreso8GWn29XvYljZ1LNYhEg',
    appId: '1:668353511665:ios:6962646536e5af85666950',
    messagingSenderId: '668353511665',
    projectId: 'barkgenius-finalproject',
    storageBucket: 'barkgenius-finalproject.appspot.com',
    iosBundleId: 'com.example.barkGeniusApp.RunnerTests',
  );
}
